### ISSUE TITLE
Error occurred applying transform of coremod wings_core.js function ActiveRenderInfoTransformer

### ISSUE THREAD

**Issue by Dinlop** [pau101/Wings#100]
Error occurred applying transform of coremod wings_core.js function ActiveRenderInfoTransformer
<eval>:372:12 Failed to find instruction
	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$109$11061A$\^eval\_.L:3$atFirst$L:363$L:364(<eval>:372)
	at jdk.nashorn.internal.scripts.Script$Recompilation$108$10147AJA$\^eval\_.L:3$addTransformer-1$L:333$L:337(<eval>:338)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1604)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1607)
	at jdk.nashorn.internal.scripts.Script$Recompilation$107$9871A$\^eval\_.L:3$addTransformer-1$L:333(<eval>:337)
	at jdk.nashorn.internal.scripts.Script$Recompilation$106$8875AJA$\^eval\_.L:3$addTransformer$transformer$L:302(<eval>:303)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1604)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1607)
	at jdk.nashorn.internal.scripts.Script$Recompilation$105$8822A$\^eval\_.L:3$addTransformer$transformer(<eval>:302)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110)
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18)
	at net.minecraftforge.coremod.NashornFactory$$Lambda$419/1728554175.apply(Unknown Source)
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18)
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10)
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38)
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41)
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:117)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142)
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97)
	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$444/579983776.buildTransformedClassNodeFor(Unknown Source)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:214)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:202)
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1007)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:997)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:885)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:730)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$485/1872627924.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by unknown-gd** [comment]
```Error occurred applying transform of coremod wings_core.js function ActiveRenderInfoTransformer
<eval>:372:12 Failed to find instruction
	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$117$11061A$\^eval\_.L:3$atFirst$L:363$L:364(<eval>:372)
	at jdk.nashorn.internal.scripts.Script$Recompilation$116$10147AJA$\^eval\_.L:3$addTransformer-1$L:333$L:337(<eval>:338)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1604)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1607)
	at jdk.nashorn.internal.scripts.Script$Recompilation$115$9871A$\^eval\_.L:3$addTransformer-1$L:333(<eval>:337)
	at jdk.nashorn.internal.scripts.Script$Recompilation$114$8875AJA$\^eval\_.L:3$addTransformer$transformer$L:302(<eval>:303)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1604)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1607)
	at jdk.nashorn.internal.scripts.Script$Recompilation$113$8822A$\^eval\_.L:3$addTransformer$transformer(<eval>:302)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110)
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18)
	at net.minecraftforge.coremod.NashornFactory$$Lambda$435/1262573693.apply(Unknown Source)
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18)
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10)
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38)
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41)
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:117)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142)
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97)
	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$463/1941639991.buildTransformedClassNodeFor(Unknown Source)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:222)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:207)
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2005)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1017)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1007)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:895)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:867)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:775)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$499/1839548688.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[14:30:91] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[14:30:91] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[14:30:94] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[14:30:16] [main/ERROR]: Error occurred applying transform of coremod wings_core.js function ActiveRenderInfoTransformer
<eval>:372:12 Failed to find instruction
	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$117$11061A$\^eval\_.L:3$atFirst$L:363$L:364(<eval>:372)
	at jdk.nashorn.internal.scripts.Script$Recompilation$116$10147AJA$\^eval\_.L:3$addTransformer-1$L:333$L:337(<eval>:338)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1604)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1607)
	at jdk.nashorn.internal.scripts.Script$Recompilation$115$9871A$\^eval\_.L:3$addTransformer-1$L:333(<eval>:337)
	at jdk.nashorn.internal.scripts.Script$Recompilation$114$8875AJA$\^eval\_.L:3$addTransformer$transformer$L:302(<eval>:303)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1604)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1607)
	at jdk.nashorn.internal.scripts.Script$Recompilation$113$8822A$\^eval\_.L:3$addTransformer$transformer(<eval>:302)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110)
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18)
	at net.minecraftforge.coremod.NashornFactory$$Lambda$435/1262573693.apply(Unknown Source)
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18)
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10)
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38)
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41)
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:117)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:204)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
	at net.minecraft.client.main.Main.main(Main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$499/1839548688.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)```
