### ISSUE TITLE
Potential issue with B3M (Time-Speed Mod)

### ISSUE THREAD

**Issue by SandwichHorror** [pau101/Wings#52]
[B3M (Time-speed mod)](https://www.curseforge.com/minecraft/mc-mods/time-speed-mod) should be the only mod in the pack I'm using that alters sun angles at all, but even with that mod's options turned off I get this crash upon loading a world with Wings installed.

Description: Exception in server tick loop

```
java.lang.NullPointerException
    at net.minecraft.world.World.getCelestialAngle(World.java:1540)
    at net.minecraft.world.World.getSunBrightnessFactor(World.java:1448)
    at net.minecraft.world.WorldProvider.getSunBrightnessFactor(WorldProvider.java:447)
    at net.minecraft.world.World.calculateSkylightSubtracted(World.java:1434)
    at net.minecraft.world.World.calculateInitialSkylight(World.java:2529)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:121)
    at net.optifine.override.WorldServerOF.<init>(WorldServerOF.java:27)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:94)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:209)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by pau101** [comment]
Thanks for reporting!

If you uninstall the wings mod you do no experience this crash correct?

**Comment by pau101** [comment]
Closing do to inactivity
